name: dependencias
description: "Gerencia as dependencias do sistema"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  flutter_modular: 6.3.4
  google_fonts: 6.2.1
  path: 1.9.0 
  sqflite: 2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

